// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Back_End.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240105144527_RestaurantCreate")]
    partial class RestaurantCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Back_End.Models.Restaurant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cuisines")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhotosUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Restaurants");

                    b.HasData(
                        new
                        {
                            Id = 2100702L,
                            Address = "2nd Floor, Adityam Building, Ulubari, Guwahati",
                            City = "Guwahati",
                            Cuisines = "North Indian",
                            Description = "Barbeque Nation is a restaurant that goes above and beyond the �unlimited food� experience. The brand strives to deliver a great customer experience. So the reinvented BBQ Nation is another step in that direction.",
                            Name = "Barbeque Nation",
                            PhotosUrl = "https://www.businessinsider.in/photo/81662629/barbeque-nation-ipo-issues-opens-today-should-you-subscribe.jpg"
                        },
                        new
                        {
                            Id = 16608059L,
                            Address = "94 Murray St, Tanunda, SA",
                            City = "Tanunda",
                            Cuisines = "Modern Australian, Australian",
                            Description = "Barbeque Nation 2",
                            Name = "1918 Bistro & Grill",
                            PhotosUrl = "https://media1.agfg.com.au/images/listing/4939/gallery/1918-bistro-grill-12.jpg"
                        },
                        new
                        {
                            Id = 16604897L,
                            Address = "49289 Us-30, Westport, OR 97016",
                            City = "Clatskanie",
                            Cuisines = "American, Breakfast, Desserts",
                            Description = "Barbeque Nation 3",
                            Name = "Berry Patch Restaurant",
                            PhotosUrl = "https://media-cdn.tripadvisor.com/media/photo-o/0c/8e/f8/2d/exterior.jpg"
                        },
                        new
                        {
                            Id = 16604896L,
                            Address = "350 Hepburn-Newstead Road, Hepburn Springs, VIC",
                            City = "Hepburn Springs",
                            Cuisines = "Italian, Fusion, Cafe",
                            Description = "Barbeque Nation 4",
                            Name = "La Trattoria of Lavandula",
                            PhotosUrl = "https://www.bestrestaurants.com.au/media/s5jpvkl4/2.jpg?width=1200&rnd=132864454952100000"
                        },
                        new
                        {
                            Id = 17536645L,
                            Address = "135 W. Main Street, Fernley, NV 89408",
                            City = "Fernley",
                            Cuisines = "Mexican",
                            Description = "Barbeque Nation 5",
                            Name = "Jehova es Mi Pastor Tacos y Burritos",
                            PhotosUrl = "https://s3-media0.fl.yelpcdn.com/bphoto/fWCgiPBAAoF_8i-aXxwl9g/l.jpg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
